### ISSUE TITLE
can not add project to my main app

### ISSUE THREAD

**Issue by pangminfu** [viavansi/mupdf-android#1]
added project reference in setting.gradle file in my main app, the gradle sync fail. below is the error message:

Error:(54, 0) No such property: repoUrl for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

i saw you had some username and password. is it because of this?

**Comment by pangminfu** [comment]
i solved it by comment  the uploadArchivespart

**Comment by milon87** [comment]
what will be the username, password and URL? can you please explain, getting same error. Thanks

**Comment by ceycochan** [comment]
> what will be the username, password and URL? can you please explain, getting same error. Thanks

//uploadArchives {
//    repositories.mavenDeployer {
//        configuration = configurations.deployerJars
//        repository(url: repoUrl) {
//            authentication(userName: repoUsername, password: repoPassword)
//        }
//        pom.version = muPdfversionName
//        pom.artifactId = "mupdf-android"
//        pom.groupId = "com.viafirma"
//    }
//}

**just comment**
