### ISSUE TITLE
License issue: MuPDF is GNU AGPL licensed

### ISSUE THREAD

**Issue by robinwatts** [viavansi/mupdf-android#9]
MuPDF is released under the GNU AGPL. As such your code also needs to be licensed under the GNU APGL. You need to supply a copy of the license terms, and a pointer to where people can get the source from.

Please either do this, or take this repo down.

Thanks.

**Comment by drmillan** [comment]
Licence terms added as COPYING

**Comment by robinwatts** [comment]
You should also add a pointer to the source for the binary libs you have provided. (Which version did 
you build? People need to be able to reproduce your builds).

Thanks for doing this!

**Comment by elaget** [comment]
Added the exact commit used to build the native files

**Comment by robinwatts** [comment]
Thanks!
